[build]
  publish = "."        # your site root (where index.html lives)
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# === Canonical redirects (extension-less → .html) ===
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301
  force = true

[[redirects]]
  from = "/reviews"
  to = "/reviews.html"
  status = 301
  force = true

[[redirects]]
  from = "/product"
  to = "/product.html"
  status = 301
  force = true