[build]
  publish = "."        # your site root (where index.html lives)
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  [[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/product.html"
  to = "/"
  status = 301
